select * from DEPARTMENTS
ALTER TABLE EMPLOYEES
Add Department VARCHAR(50)
ALTER TABLE EMPLOYEES
ALTER COLUMN SALARY FLOAT
ALTER TABLE EMPLOYEES
DROP COLUMN Departments
CREATE TABLE DepartmentS (
Departmentid INT PRIMARY KEY,
DepartmentidName VARCHAR(250));
DELETE FROM DepartmentS
WHERE Departmentid=6
UPDATE DepartmentS
SET DepartmentidName ='BEGZOD'
WHERE DepartmentID =2
TRUNCATE TABLE EMPLOYEES
Задачи среднего уровня (6)
INSERT INTO DepartmentS (Departmentid, DepartmentidName) VALUES 
('1','Otabek'),
('2','Oybek'),
('3','Elbek'),
('4','Surat'),
('5','Oktam')
select * from EMPLOYEES t WHERE t.SALARY > 5000 
INSERT INTO EMPLOYEES (Empid, Name, Salary, Department) VALUES 
('2','Oybek', 2000,'TEX'),
TRUNCATE TABLE EMPLOYEES
DROP TABLE DEPARTMENT EMPLOYEES
UPDATE TABLE EMPLOYEES
TRUNCATE TABLE EMPLOYEES
CREATE TABLE Products (
PRODUCTID INT PRIMARY KEY,
PRODUCTNAME VARCHAR(50),
CATEGORY VARCHAR(50),
PRICE DECIMAL(10, 2), CHECK (PRICE>0)
);
ALTER TABLE PRODUCTS
ADD CONSTRAINT chk_price_positive CHECK (PRICE > 0);
19ALTER TABLE PRODUCTS
ADD StockQuantity INT DEFAULT 50;
20EXEC sp_rename 'PRODUCTS.CATEGORY','PRODUCTCATEGORY', 'COLUMN';
INSERT INTO PRODUCTS (PRODUCTID,PRODUCTNAME,PRODUCTCATEGORY,PRICE,STOCKQUANTITY) VALUES
(2,'OLMA','QIZIL','5000',30),
(3,'NOK','QIZIL','6000',5000),
(4,'ANOR','QIZIL','7000',2500),
(5,'UZUM','QIZIL','7000',500),
(6,'TARVUZ','QIZIL','8000',1000);
SELECT * INTO PRODUCTS_Backup FROM PRODUCTS
EXEC SP_RENAME 'PRODUCTS', 'INVENTORY';
ALTER TABLE Inventory
ALTER COLUMN Price FLOAT;
SELECT * FROM INVENTORY
ALTER TABLE INVENTORY
